# Generated by Django 4.2.4 on 2023-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='subject_id',
            new_name='student_id',
        ),
    ]
